<div class="checkout-success">
    <p><?php echo $block->escapeHtml(__('Sorry, your payment has failed')) ?></p>
    <p><?php echo $block->escapeHtml(__("If you need further assistance do not hesitate to contact us.")) ?></p>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php echo $block->escapeUrl($block->getUrl()) ?>">
              <span><?php echo $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        </div>
    </div>
</div>
