<div class="checkout-success">
    <p><?php echo $block->escapeHtml(__('Thank you, your payment is being processed!')) ?></p>
    <p><?php echo $block->escapeHtml(__(
        'A confirmation email has been sent to you, we will contact you as soon as posible.'
)) ?></p>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php echo $block->escapeUrl($block->getUrl()) ?>">
              <span><?php echo $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        </div>
    </div>
</div>
