
<?php $secureFormData =  $this->getSecureFormData();?>
<div>
<div id="secure-payment-button"></div>
  <script>
  require(['jquery','payapiSdk'],function($){
  		<?php if($this->checkPayApiConfiguration()) { ?>
  			var secureFormData = <?php echo $secureFormData;?>;  	
			payapiSdk.configure("<?php echo $this->getPayapiPublicId(); ?>" , "<?php echo $this->getPayapiApiKey(); ?>" );
			payapiSdk.addSecurePaymentButtonToDiv(secureFormData, 'secure-payment-button', 'Buy now');
		<?php } ?>
	});
  </script>
</div>