<div class="checkout-success">
    <p><?php echo $block->escapeHtml(__('Sorry, you cancelled the payment')) ?></p>
    <p><?php echo $block->escapeHtml(__(
        'Your products are still on your shopping cart, if you do need any help do not hesitate to contact us.'
)) ?></p>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php echo $block->escapeUrl($block->getUrl()) ?>">
              <span><?php echo $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        </div>
    </div>
</div>
