<div class="checkout-success">
    <p><?php /* @escapeNotVerified */ echo __('Sorry, your payment has failed') ?></p>
    <p><?php /* @escapeNotVerified */ echo __("If you need further assistance do not hesitate to contact us."") ?></p>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
