
<div>
<?php if ($block->checkPayApiConfiguration()) {?>
<script>
require(['jquery',
        'payapiSdk'],function($){

    var $btnClicked = $("#payapi-instantbutton");
    $btnClicked.click(function(evt){
        evt.preventDefault();
        var jsonData = {
            "referenceQuoteId": window.checkoutConfig.quoteItemData[0].quote_id,
            "ipaddress":"<?php echo $block->escapeHtml($block->getVisitorIp()); ?>"
        };
        $.ajax({
            showLoader: true,
            type: "POST",
            url: "/payapipages/index/secureformgenerator",
            data: jsonData,
            success: function(data){
                payapiSdk.configure(window.checkoutConfig.payment.customPayment.payapi_public_id,
                                     window.checkoutConfig.payment.customPayment.payapi_api_key);
                payapiSdk.postData(data);
            }
        });
    });
});
</script>
  <button id="payapi-instantbutton" class="action primary checkout">
    <span><?php echo $block->escapeHtml(__('Instant Buy')) ?></span>
</button>
<?php }?>
</div>
