
<?php if($this->checkPayApiConfiguration()) { ?>

  <script>
  require(['jquery'],function($){

          var $btnClicked = $("#payapi-button<?php echo $this->getProduct()->getId(); ?>");
          $btnClicked.click(function(evt){
            evt.preventDefault();
            var productUrl = $btnClicked.closest(".product-item-info").find('.fngrsharesdk-product').attr('href');
            if($btnClicked.attr('data-mandatory') !== "1"){
              window.location = 'https://input.payapi.io/v1/webshop/'+ encodeURIComponent(productUrl);
            }else{
              window.location = productUrl;
            }
          });
	});

  </script>

  <button data-mandatory="<?php echo $this->checkMandatoryFields(); ?>" id="payapi-button<?php echo $this->getProduct()->getId(); ?>" class="action primary tocart payapi-button" style="margin-bottom:10px"><span><?php /* @escapeNotVerified */ echo __('Instant Buy') ?></span></button>  
  
<?php } ?>