<div class="checkout-success">
    <p>Thank you, your payment is being processed!</p>
    <p>A confirmation email has been sent to you, we will contact you as soon as posible.</p>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
